//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferAm
    {
        public int sno { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Account_No { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> ToTransfer { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
