//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public decimal Account_No { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public Nullable<decimal> CNP { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Date { get; set; }
    }
}
